version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://legalai:legalai123@postgres:5432/legalai
      - REDIS_URL=redis://redis:6379
      - GOOGLE_DRIVE_CREDENTIALS_PATH=/app/credentials/google-credentials.json
      - MODEL_PATH=/app/models
      - VECTOR_DB_PATH=/app/vector_db
    volumes:
      - ./credentials:/app/credentials
      - ./models:/app/models
      - ./vector_db:/app/vector_db
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
    networks:
      - legalai-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=legalai
      - POSTGRES_USER=legalai
      - POSTGRES_PASSWORD=legalai123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - legalai-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - legalai-network

  celery:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://legalai:legalai123@postgres:5432/legalai
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./credentials:/app/credentials
      - ./models:/app/models
      - ./vector_db:/app/vector_db
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
    networks:
      - legalai-network

  flower:
    build: .
    command: celery -A app.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://legalai:legalai123@postgres:5432/legalai
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
      - celery
    networks:
      - legalai-network

volumes:
  postgres_data:
  redis_data:

networks:
  legalai-network:
    driver: bridge